version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nextjs-yt-dlp-list-channels"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-148nh4a4hjibx"
s3_prefix = "nextjs-yt-dlp-list-channels"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []