version: '3.3'
services:
  nextjs:
    build:
      context: .
      args:
        - NEXT_PUBLIC_BASE_API_URL=https://api.youtube.hxrsmurf.info
        - NODE_ENV=production
    ports:
      - 3000:3000
