Transform: AWS::Serverless-2016-10-31

Description: NextJS-13 YouTube-DLP

Parameters:
  ApiUrl:
    Type: String
    Default: http://placeholder.homelabwithkevin.com:8080

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: nextjs-13-yt-dlp-channels

  NextJSUser:
    Type: 'AWS::IAM::User'
    Properties: {}

  NextJSPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Users:
        - !Ref NextJSUser
      PolicyName: nextjs13-dynamodb
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:Scan'
              - 'dynamodb:Query'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:ConditionCheckItem'
            Resource:
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Table}
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Table}/index/*