Transform: AWS::Serverless-2016-10-31

Description: NextJS-13 YouTube-DLP

Parameters:
  ApiUrl:
    Type: String
    Default: http://placeholder.homelabwithkevin.com:8080
  PythonVersion:
    Type: String
    Default: python3.9
  LayerStackName:
    Type: String
    Default: python-lambda-layers

  EventBridgeState:
    Type: String
    Default: ENABLED
    AllowedValues:
      - DISABLED
      - ENABLED

Outputs:
  ApiUrl:
    Value: !GetAtt ServerlessHttpApi.ApiEndpoint

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  QueueDownload:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 900

  TableChannels:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: nextjs-13-yt-dlp-channels

  TableVideos:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: nextjs-13-yt-dlp-videos

  NextJSUser:
    Type: 'AWS::IAM::User'
    Properties: {}

  NextJSPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Users:
        - !Ref NextJSUser
      PolicyName: nextjs13-dynamodb
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:Scan'
              - 'dynamodb:Query'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:ConditionCheckItem'
            Resource:
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:{TableChannels}/$
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:{TableChannels}/$/index/*
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:{TableVideos}/$
              - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:{TableVideos}/$/index/*

  ListChannels:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: !Ref PythonVersion
      CodeUri: list-channels
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          TableName: !Ref TableChannels
          QueueUrl: !Ref Queue
      Events:
        EventBridge:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(1 hours)
            State: !Ref EventBridgeState
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableChannels
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName

  ParseUrl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: !Ref PythonVersion
      CodeUri: parse-url
      MemorySize: 256
      Timeout: 60
      Layers:
        - Fn::ImportValue:
            Fn::Sub: '${LayerStackName}-ytdlp'
      Environment:
        Variables:
          TableChannels: !Ref TableChannels
          TableVideos: !Ref TableVideos
          QueueUrl: !Ref Queue
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
        SQS:
          Type: SQS
          Properties:
             BatchSize: 1
             Queue: !GetAtt Queue.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableChannels
        - DynamoDBCrudPolicy:
            TableName: !Ref TableVideos
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName

  Downloader:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: !Ref PythonVersion
      CodeUri: downloader
      MemorySize: 2048
      Timeout: 900
      Layers:
        - Fn::ImportValue:
            Fn::Sub: '${LayerStackName}-ffmpeg'
        - Fn::ImportValue:
            Fn::Sub: '${LayerStackName}-requests'
        - Fn::ImportValue:
            Fn::Sub: '${LayerStackName}-ytdlp'
      Environment:
        Variables:
          ApiUrl: !Ref ApiUrl
          QueueUrl: !Ref Queue
          TableName: !Ref TableChannels
      Events:
        SQS:
          Type: SQS
          Properties:
             BatchSize: 1
             Queue: !GetAtt QueueDownload.Arn