Transform: AWS::Serverless-2016-10-31

Description: NextJS-13 YouTube-DLP

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: nextjs-13-yt-dlp-channels

  ApiUrl:
    Type: String
    Properties:
      Default: http://placeholder.homelabwithkevin.com:8080

  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: python
      Timeout: 900
      Environment:
        Variables:
          TableName: !Ref Table
          QueueUrl: !Ref Queue
      Layers:
        - !Ref Layer
        - !Ref ffmpeg
      Events:
        PostAPI:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName

  SQSParser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: python
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          TableName: !Ref Table
          QueueUrl: !Ref Queue
          ApiUrl: !Ref ApiUrl
      Layers:
        - !Ref Layer
        - !Ref ffmpeg
      Events:
        SQS:
          Type: SQS
          Properties:
             BatchSize: 1
             Queue: !GetAtt Queue.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  ListChannels:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: list-channels
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TableName: !Ref Table
          QueueUrl: !Ref Queue
      Events:
        EventBridge:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(1 hours)
            State: ENABLED
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
        - SQSSendMessagePolicy:
            QueueName: !GetAtt Queue.QueueName

  Downloader:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: downloader
      MemorySize: 256
      Timeout: 900
      Environment:
        Variables:
          TableName: !Ref Table
          QueueUrl: !Ref Queue
          ApiUrl: !Ref ApiUrl
      Layers:
        - !Ref requests
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: yt-dlp
      CompatibleRuntimes:
        - python3.9
      Description: YouTube-DLP (Python)
      LayerName: YouTube-dlp
    Metadata:
      BuildMethod: python3.9

  ffmpeg:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ffmpeg
      CompatibleRuntimes:
        - python3.9
      Description: ffmpeg (python)
      LayerName: ffmpeg
    Metadata:
      BuildMethod: python3.9

  requests:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: requests
      CompatibleRuntimes:
        - python3.9
      Description: requests (python)
      LayerName: requests-py
    Metadata:
      BuildMethod: python3.9