version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ytdlp-kvch-spot-instance"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-148nh4a4hjibx"
s3_prefix = "ytdlp-kvch-spot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []