Transform: AWS::Serverless-2016-10-31
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.7
      CodeUri: python
      Timeout: 5
      Environment:
        Variables:
          B2_KEY_ID: example
          B2_KEY: example
          B2_BUCKET: example
      Events:
        PostAPI:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - AmazonEC2FullAccess