web:
  image: nginx
  volumes:
   - /home/:/mnt/local:ro
  #  - ./nginx.conf:/etc/nginx/nginx.conf:ro
   - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  ports:
   - "8081:80"
  environment:
   - NGINX_PORT=80