Transform: AWS::Serverless-2016-10-31
Parameters:
  RestrictedIps:
    Type: String
    Default: 8.8.8.8, 1.1.1.1
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.7
      CodeUri: python
      Timeout: 5
      Environment:
        Variables:
          B2_KEY_ID: example
          B2_KEY: example
          B2_BUCKET: example
          RESTRICTED_IPS: !Ref RestrictedIps
      Events:
        PostAPI:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - AmazonEC2FullAccess