Transform: AWS::Serverless-2016-10-31
Parameters:
  B2KeyId:
    Type: String
    Default: example
  B2Key:
    Type: String
    Default: example
  B2Bucket:
    Type: String
    Default: example

  RestrictedIps:
    Type: String
    Default: 8.8.8.8, 1.1.1.1

  BunnyCDNLibrary:
    Type: String
    Default: example
  BunnyCDNKey:
    Type: String
    Default: example

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.7
      CodeUri: python
      Timeout: 5
      Environment:
        Variables:
          B2_KEY_ID: !Ref B2KeyId
          B2_KEY: !Ref B2Key
          B2_BUCKET: !Ref B2Bucket
          RESTRICTED_IPS: !Ref RestrictedIps
          BUNNYCDN_LIBRARY: !Ref BunnyCDNLibrary
          BUNNYCDN_KEY: !Ref BunnyCDNKey
      Events:
        PostAPI:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - AmazonEC2FullAccess